### ISSUE TITLE
Village map

### ISSUE THREAD

**Issue by Timmytheghosty** [ZealStudio/HeroPath#28]

**Comment by Fire1Shark** [comment]
![Image](https://github.com/ZealStudio/HeroPath/assets/158119922/12b903d6-74a6-4c3f-a3fa-2a7c3141d941)

**Comment by Fire1Shark** [comment]
![Image](https://github.com/ZealStudio/HeroPath/assets/158119922/d4ef2b0d-683a-4673-846b-8b47e851b239)
