### ISSUE TITLE
Forest Start Zone

### ISSUE THREAD

**Issue by Timmytheghosty** [ZealStudio/HeroPath#29]
![Image](https://github.com/ZealStudio/HeroPath/assets/157427377/b6355dfe-f3eb-4664-8647-93af3e3736f7)

**Comment by Timmytheghosty** [comment]
Black = Tutorial
Red = Fight Area
Gold = Item pickups
This is the first area for the player the setting is a Dark and Dense Forest. The player does the Tutorial it the bottom left corner after which they have to cross a bridge. If the player decides to up or down before the bridge they are able to find some items. After crossing the bridge there is items across and random encounters start in the red zone. Then the player makes their way towards the next area into the cave.

**Comment by Bro-dep** [comment]
More side paths and maybe sign posts to show right direction

**Comment by Fire1Shark** [comment]
![Image](https://github.com/ZealStudio/HeroPath/assets/158119922/d09b3326-c172-4485-8bbe-4c7be2e11e1b)

**Comment by Fire1Shark** [comment]
![Image](https://github.com/ZealStudio/HeroPath/assets/158119922/9609a3c1-95be-4c0b-b962-a11f76bd06df)

**Comment by Bro-dep** [comment]
For #17
